sales_management/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('callback','LoginController@callback');

// Route::group(['middleware' => 'SSOAuth'],function(){
    Route::get('/','DashboardController@index')->name('dashboard');
    Route::resource('agent-type','AgentTypeController')->except(['show']);
    Route::resource('branch','BranchController');
    Route::resource('service','ServiceController')->except(['show']);
    Route::resource('delivery-transaction','DeliveryTransactionController');

    // item delivery
    Route::group(['prefix' => 'delivery-transaction/{id}'],function(){
        Route::resource('item-delivery','ItemDeliveryController')->only(['create','store']);
    });
// });

sales_management/app/Http/Controllers/ItemDeliveryController.php
<?php

namespace App\Http\Controllers;

use App\Model\ItemDelivery;
use Illuminate\Http\Request;
use App\Http\Requests\ItemDeliveryRequest;

class ItemDeliveryController extends Controller
{

    public function create($deliveryTransactionId)
    {
        return view('admin.item_delivery.create',compact('deliveryTransactionId'));
    }

    public function store(ItemDeliveryRequest $request,$deliveryTransactionId)
    {
        for($i = 0; $i < count($request->item_name); $i++)
        {
            ItemDelivery::create([
                'delivery_transaction_id'   => $deliveryTransactionId,
                'item_name'                 => $request->item_name[$i],
                'qty'                       => $request->qty[$i],
                'price'                     => $request->price[$i],
                'description'               => $request->description[$i],
            ]);
        }

        return redirect()->route('delivery-transaction.show',$deliveryTransactionId);
    }
}

sales_management/resources/views/admin/item_delivery/create.blade.php
@extends('admin.layouts.app')

@section('head')
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/new-article.css') }}">
@endsection

@section('content')
<div id="content">
    <header class="clearfix">
        <h2 class="pull-left page_title">Create New delivery transaction</h2>
    </header>

    <div class="content-inner">
        <div class="form-wrapper">
            <form class="form-horizontal" action="{{ route('item-delivery.store',$deliveryTransactionId) }}" method="POST">
                @csrf
                <input type="hidden" name="total_input" id="total_input" value="{{ $errors->any() ? old('total_input') : 1 }}">
                <table class="table" id="item_content">
                    <tr>
                        <th>Item Name</th>
                        <th>Description</th>
                        <th width="20px">quantity</th>
                        <th>price</th>
                        <th>&nbsp;</th>
                    </tr>
                    @if($errors->any())
                        @for($i = 0; $i < old('total_input'); $i++)
                            <tr id="content_{{ $i + 1 }}">
                                <td class="{{ $errors->has('item_name.'.$i)  ? 'has-error' : 'has-success'}}">
                                    <input type="text" name="item_name[]" class="form-control" id="" placeholder="Item Name" value="{{ old('item_name.'.$i) }}">
                                    <span class="help-block">{{$errors->first('item_name.'.$i) }}</span>
                                </td>
                                 <td class="{{ $errors->has('description.'.$i)  ? 'has-error' : 'has-success'}}">
                                    <input type="text" name="description[]" class="form-control" id="" placeholder="Description" value="{{ old('description.'.$i) }}">
                                    <span class="help-block">{{$errors->first('description.'.$i) }}</span>
                                </td>
                                <td class="{{ $errors->has('qty.'.$i)  ? 'has-error' : 'has-success'}}">
                                    <input type="text" name="qty[]" class="form-control" id="" placeholder="Qty" value="{{ old('qty.'.$i) }}">
                                    <span class="help-block">{{$errors->first('qty.'.$i) }}</span>
                                </td>
                                <td class="{{ $errors->has('price.'.$i)  ? 'has-error' : 'has-success'}}">
                                    <input type="text" name="price[]" class="form-control" id="" placeholder="Price" value="{{ old('price.'.$i) }}">
                                    <span class="help-block">{{$errors->first('price.'.$i) }}</span>                                    
                                </td>
                                <td>
                                    @if($i == 0)
                                        <button class="btn btn-success btn-add" type="button"><span class="glyphicon glyphicon-plus"></span></button>
                                    @else
                                        <button class="btn btn-danger btn-remove" id="{{ $i + 1 }}" type="button"><span class="glyphicon glyphicon-minus"></span></button>
                                    @endif
                                </td>
                            </tr>
                        @endfor
                    @else
                        <tr>
                            <td><input type="text" name="item_name[]" class="form-control" id="" placeholder="Item Name" value=""></td>
                            <td><input type="text" name="description[]" class="form-control" id="" placeholder="Description" value=""></td>
                            <td><input type="text" name="qty[]" class="form-control" id="" placeholder="Qty" value=""></td>
                            <td><input type="text" name="price[]" class="form-control" id="" placeholder="Price" value=""></td>
                            <td><button class="btn btn-success btn-add" type="button"><span class="glyphicon glyphicon-plus"></span></button></td>
                        </tr>
                    @endif
                </table>
              <!-- /.box-footer -->
                <div class="clearfix">
                    <button type="submit" class="btn btn-primary pull-right">Save</button>
                </div>
              
            </form>
        </div>
    </div>
</div>
@endsection

@section('script')
    <script type="text/javascript">
        $(function(){
            var a = "{{ $errors->any() ? old('total_input') : 1 }}";
            $(document).on('click','.btn-add',function(){
                a++;
                var html    = '<tr id="content_'+a+'">';
                    html   += '<td><input type="text" name="item_name[]" class="form-control" id="" placeholder="Item Name" value=""></td>';
                    html   += '<td><input type="text" name="description[]" class="form-control" id="" placeholder="Description" value=""></td>';
                    html   += '<td><input type="text" name="qty[]" class="form-control" id="" placeholder="Qty" value=""></td>';
                    html   += '<td><input type="text" name="price[]" class="form-control" id="" placeholder="Price" value=""></td>';
                    html   += '<td><button class="btn btn-danger btn-remove" type="button" id="'+a+'"><span class="glyphicon glyphicon-minus"></span></button></td>';
                    html   += '</tr>';   
                    $('#item_content').append(html);
                    $('#total_input').val(a);
            });

             $(document).on('click','.btn-remove',function(){
                var id = $(this).attr("id");
                $('#content_'+id).remove();
                a--;
                $('#total_input').val(a);
            });

        });
    </script>
@endsection

sales_management/resources/views/admin/item_delivery/edit.blade.php
@extends('admin.layouts.app')

@section('head')
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/new-article.css') }}">
@endsection

@section('content')
<div id="content">
    <header class="clearfix">
        <h2 class="pull-left page_title">Create New delivery transaction</h2>
        <a class="btn btn-sm btn-primary pull-right" href="{{ route('delivery-transaction.index') }}" role="button">Back</a>
    </header>

    <div class="content-inner">
        <div class="form-wrapper">
            <form class="form-horizontal" action="{{ route('delivery-transaction.update',$deliveryTransaction->id) }}" method="POST">
                @csrf
                {{ method_field('PATCH') }}
                <div class="box-body">

                @if($errors->any())
                    <div class="form-group {{ $errors->has('receipt_code') ? 'has-error' : 'has-success' }}">
                @else
                    <div class="form-group">
                @endif
                    <label for="" class="col-sm-2 control-label">Receipt Code</label>
                    <div class="col-sm-10">
                        <input type="text" name="receipt_code" class="form-control" id="" placeholder="Receipt Code" value="{{ $errors->any() ? old('receipt_code') : $deliveryTransaction->receipt_code }}">
                        <span class="help-block">{{ $errors->first('receipt_code') }}</span>
                    </div>
                </div>

                @if($errors->any())
                    <div class="form-group {{ $errors->has('agent_address') ? 'has-error' : 'has-success' }}">
                @else
                    <div class="form-group">
                @endif
                    <label for="" class="col-sm-2 control-label">Agent Address</label>
                    <div class="col-sm-10">
                        <input type="text" name="agent_address" class="form-control" id="" placeholder="Agent Address" value="{{ $errors->any() ? old('agent_address') : $deliveryTransaction->agent_address }}">
                        <span class="help-block">{{ $errors->first('agent_address') }}</span>
                    </div>
                </div>

                @if($errors->any())
                    <div class="form-group {{ $errors->has('bill_to') ? 'has-error' : 'has-success' }}">
                @else
                    <div class="form-group">
                @endif
                    <label for="" class="col-sm-2 control-label">Bill To</label>
                    <div class="col-sm-10">
                        <input type="text" name="bill_to" class="form-control" id="" placeholder="Bill To" value="{{ $errors->any() ? old('bill_to') : $deliveryTransaction->bill_to }}">
                        <span class="help-block">{{ $errors->first('bill_to') }}</span>
                    </div>
                </div>

                @if($errors->any())
                    <div class="form-group {{ $errors->has('ship_to') ? 'has-error' : 'has-success' }}">
                @else
                    <div class="form-group">
                @endif
                    <label for="" class="col-sm-2 control-label">Ship To</label>
                    <div class="col-sm-10">
                        <input type="text" name="ship_to" class="form-control" id="" placeholder="Ship To" value="{{ $errors->any() ? old('ship_to') : $deliveryTransaction->ship_to }}">
                        <span class="help-block">{{ $errors->first('ship_to') }}</span>
                    </div>
                </div>

                @if($errors->any())
                    <div class="form-group {{ $errors->has('address_ship') ? 'has-error' : 'has-success' }}">
                @else
                    <div class="form-group">
                @endif
                    <label for="" class="col-sm-2 control-label">Address Ship</label>
                    <div class="col-sm-10">
                        <textarea name="address_ship" id="" cols="30" rows="5" class="form-control" placeholder="Address Ship">{{ $errors->any() ? old('address_ship') : $deliveryTransaction->address_ship }}</textarea>
                        <span class="help-block">{{ $errors->first('address_ship') }}</span>
                    </div>
                </div>

                @if($errors->any())
                    <div class="form-group {{ $errors->has('due_date') ? 'has-error' : 'has-success' }}">
                @else
                    <div class="form-group">
                @endif
                    <label for="" class="col-sm-2 control-label">Due Date</label>
                    <div class="col-sm-10">
                        <input type="date" name="due_date" class="form-control" id="" placeholder="Due Date" value="{{ $errors->any() ? old('due_date') : $deliveryTransaction->due_date }}">
                        <span class="help-block">{{ $errors->first('due_date') }}</span>
                    </div>
                </div>

                </div>
                <!-- /.box-body -->
                <div class="clearfix">
                    <button type="submit" class="btn btn-primary pull-right">Save</button>
                </div>
              <!-- /.box-footer -->
            </form>
        </div>
    </div>
</div>
@endsection

sales_management/resources/views/admin/item_delivery/index.blade.php
@extends('admin.layouts.app')

@section('head')
<link rel="stylesheet" href="{{ asset('assets/css/index.css') }}">
@endsection

@section('content')
<div id="dashboard-con">
    <div class="row">
        <div class="col-md-12 dashboard-left-cell">
            <div class="admin-content-con">
            <header class="clearfix">
                <h5 class="pull-left page_title">Delivery Transaction</h5>
                <a class="btn btn-sm btn-primary pull-right" href="{{ route('delivery-transaction.create') }}" role="button">Create new Delivery</a>
            </header>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>no</th>
                        <th>receipt code</th>
                        <th>agent address</th>
                        <th>bill to</th>
                        <th>ship to</th>
                        <th>due date</th>
                        <th>action</th>
                    </tr>
                </thead>
                <tbody>
                @foreach($results as $result)
                    <tr>
                        <td>no</td>
                        <td>{{ $result->receipt_code }}</td>
                        <td>{{ $result->agent_address }}</td>
                        <td>{{ $result->bill_to }}</td>
                        <td>{{ $result->ship_to }}</td>
                        <td>{{ $result->due_date }}</td>
                        <td>
                            <a class="btn btn-xs btn-warning" href="{{ route('delivery-transaction.edit',$result->id) }}" role="button">edit</a>
                            <a class="btn btn-xs btn-primary" href="{{ route('delivery-transaction.show',$result->id) }}" role="button">view</a>
                            <form action="{{ route('delivery-transaction.destroy',$result->id) }}" method="POST" style="display:inline;">
                                @csrf
                                {{ method_field('DELETE') }}
                                <button class="btn btn-xs btn-danger">del</button>    
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            <div class="clearfix">
            <a href="#" class="pull-right text-link">view all articles</a>
            </div>
            </div>
        </div>
    </div>
</div>
@endsection

sales_management/resources/views/admin/item_delivery/show.blade.php
@extends('admin.layouts.app')

@section('head')
<link rel="stylesheet" href="{{ asset('assets/css/index.css') }}">
@endsection

@section('content')
<div id="dashboard-con">
    <div class="row">
        <div class="col-md-12">
            <div class="admin-content-con clearfix">
                <header class="clearfix">
                <h5 class="pull-left page_title">Detail Delivery Transaction</h5>
                <a class="btn btn-sm btn-primary pull-right" href="{{ route('delivery-transaction.index') }}" role="button">Back</a>
            </header>

                <table class="table table-bordered">
                    <tr>
                        <th>receipt code</th>
                        <td>{{ $deliveryTransaction->receipt_code }}</td>
                    </tr>
                    <tr>
                        <th>agent address</th>
                        <td>{{ $deliveryTransaction->agent_address }}</td>
                    </tr>
                    <tr>
                        <th>bill to</th>
                        <td>{{ $deliveryTransaction->bill_to }}</td>
                    </tr>
                    <tr>
                        <th>ship to</th>
                        <td>{{ $deliveryTransaction->ship_to }}</td>
                    </tr>
                    <tr>
                        <th>address ship</th>
                        <td>{{ $deliveryTransaction->address_ship }}</td>
                    </tr>
                    <tr>
                        <th>due date</th>
                        <td>{{ $deliveryTransaction->due_date }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

     <div class="row">
        <div class="col-md-12">
            <div class="admin-content-con clearfix">
                <header class="clearfix">
                <h5 class="pull-left page_title">Item Delivery</h5>
                <a class="btn btn-sm btn-primary pull-right" href="{{ route('item-delivery.create',$deliveryTransaction->id) }}" role="button">Create New Item Delivery</a>
            </header>

                <table class="table table-bordered">
                    <tr>
                        <th>quantity</th>
                        <td>{{ $deliveryTransaction->agent_address }}</td>
                    </tr>
                    <tr>
                        <th>description</th>
                        <td>{{ $deliveryTransaction->bill_to }}</td>
                    </tr>
                    <tr>
                        <th>price</th>
                        <td>{{ $deliveryTransaction->ship_to }}</td>
                    </tr>
                    <tr>
                        <th>Total</th>
                        <td>-</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection 