sales_management/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('callback','LoginController@callback');

// Route::group(['middleware' => 'SSOAuth'],function(){
    Route::get('/','DashboardController@index')->name('dashboard');
    Route::resource('agent-type','AgentTypeController')->except(['show']);
    Route::resource('branch','BranchController');
    Route::resource('service','ServiceController')->except(['show']);
    Route::resource('delivery-transaction','DeliveryTransactionController');

    // item delivery
    Route::group(['prefix' => 'delivery-transaction/{id}'],function(){
        Route::resource('item-delivery','ItemDeliveryController')->only(['create','store']);
    });
// });

sales_management/app/Http/Controllers/AgentTypeController.php
<?php

namespace App\Http\Controllers;

use App\Model\AgentType;
use Illuminate\Http\Request;
use App\Http\Requests\AgentTypeRequest;

class AgentTypeController extends Controller
{
    public function index()
    {
        $results = AgentType::all();
        return view('admin.agent_type.index',compact('results'));
    }

    public function create()
    {
        return view('admin.agent_type.create');
    }

    public function store(AgentTypeRequest $request)
    {
        AgentType::create($request->all());
        return redirect()->route('agent-type.index');
    }

    public function edit(AgentType $agentType)
    {
        return view('admin.agent_type.edit',compact('agentType'));
    }

    public function update(Request $request, AgentType $agentType)
    {
        $agentType->update($request->all());
        return redirect()->route('agent-type.index');
    }

    public function destroy(AgentType $agentType)
    {
        $agentType->delete();
        return redirect()->route('agent-type.index');
    }
}

sales_management/resources/views/admin/agent_type/create.blade.php
@extends('admin.layouts.app')

@section('head')
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/new-article.css') }}">
@endsection

@section('content')
<div id="content">
    <header class="clearfix">
        <h5 class="pull-left page_title">Create new agent types</h5>
        <a class="btn btn-sm btn-primary pull-right" href="{{ route('agent-type.index') }}" role="button">Back</a>
    </header>

    <div class="content-inner">
        <div class="form-wrapper">
            <form action="{{ route('agent-type.store') }}" method="POST">
                @csrf
                @if($errors->any())
                    <div class="form-group {{ $errors->has('type') ? 'has-error' : 'has-success' }}">
                @else
                    <div class="form-group">
                @endif
                    <label>Nama tipe agen</label>
                    <input type="text" name="type" class="form-control" placeholder="nama type agen" value="{{ old('type') }}">
                    <span>{{ $errors->first('type') }}</span>
                </div>
                

                <div class="clearfix">
                    <button type="submit" class="btn btn-primary pull-right">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

sales_management/resources/views/admin/agent_type/edit.blade.php
@extends('admin.layouts.app')

@section('head')
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/new-article.css') }}">
@endsection

@section('content')
<div id="content">
    <header class="clearfix">
        <h5 class="pull-left page_title">Edit agent types</h5>
        <a class="btn btn-sm btn-primary pull-right" href="{{ route('agent-type.index') }}" role="button">Back</a>
    </header>

    <div class="content-inner">
        <div class="form-wrapper">
            <form action="{{ route('agent-type.update',$agentType->id) }}" method="POST">
                @csrf
                {{ method_field('PATCH') }}
                @if($errors->any())
                    <div class="form-group {{ $errors->has('type') ? 'has-error' : 'has-success' }}">
                @else
                    <div class="form-group">
                @endif
                    <label>Nama tipe agen</label>
                    <input type="text" name="type" class="form-control" placeholder="nama type agen" value="{{ $errors->any() ? old('type') : $agentType->type }}">
                    <span>{{ $errors->first('type') }}</span>
                </div>
                

                <div class="clearfix">
                    <button type="submit" class="btn btn-primary pull-right">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

sales_management/resources/views/admin/agent_type/index.blade.php
@extends('admin.layouts.app')

@section('head')
<link rel="stylesheet" href="{{ asset('assets/css/index.css') }}">
@endsection

@section('content')
<div id="dashboard-con">
    <div class="row">
        <div class="col-md-12">
            <div class="admin-content-con clearfix">
                <header class="clearfix">
                    <h5 class="pull-left page_title">Agent types</h5>
                    <a class="btn btn-sm btn-primary pull-right" href="{{ route('agent-type.create') }}" role="button">Create new Agent Type</a>
                </header>

                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Agent Type Name</th>
                            <th>Action</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($results as $key => $result)
                            <tr>
                                <td>{{ $key + 1 }}</td>
                                <td>{{ $result->type }}</td>
                                <td>
                                <a href="{{ route('agent-type.edit',$result->id) }}" class="btn btn-warning btn-xs">edit</a>
                                <form action="{{ route('agent-type.destroy',$result->id) }}" method="POST" style="display:inline-block;">
                                    @csrf
                                    {{ method_field('DELETE') }}
                                    <button type="submit" class="btn btn-danger btn-xs">delete</button>
                                </form>    
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection