sales_management/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('callback','LoginController@callback');

// Route::group(['middleware' => 'SSOAuth'],function(){
    Route::get('/','DashboardController@index')->name('dashboard');
    Route::resource('agent-type','AgentTypeController')->except(['show']);
    Route::resource('branch','BranchController');
    Route::resource('service','ServiceController')->except(['show']);
    Route::resource('delivery-transaction','DeliveryTransactionController');

    // item delivery
    Route::group(['prefix' => 'delivery-transaction/{id}'],function(){
        Route::resource('item-delivery','ItemDeliveryController')->only(['create','store']);
    });
// });

sales_management/app/Http/Controllers/DeliveryTransactionController.php
<?php

namespace App\Http\Controllers;

use App\Model\DeliveryTransaction;
use App\Model\Service;
use Illuminate\Http\Request;
use App\Http\Requests\DeliveryTransactionRequest;

class DeliveryTransactionController extends Controller
{

    public function index()
    {
        $results = DeliveryTransaction::all();
        return view('admin.delivery_transaction.index',compact('results'));
    }

    public function create()
    {
        $services = Service::all();
        return view('admin.delivery_transaction.create',compact('services'));
    }

    public function store(DeliveryTransactionRequest $request)
    {
        $data = DeliveryTransaction::create($request->all());
        return redirect()->route('item-delivery.create',$data->id);
    }

    public function show(DeliveryTransaction $deliveryTransaction)
    {
        return view('admin.delivery_transaction.show',compact('deliveryTransaction'));
    }

    public function edit(DeliveryTransaction $deliveryTransaction)
    {
        return view('admin.delivery_transaction.edit',compact('deliveryTransaction'));
    }

    public function update(DeliveryTransactionRequest $request, DeliveryTransaction $deliveryTransaction)
    {
        $deliveryTransaction->update($request->all());
        return redirect()->route('delivery-transaction.index');
    }

    public function destroy(DeliveryTransaction $deliveryTransaction)
    {
        $deliveryTransaction->delete();
        return redirect()->route('delivery-transaction.index');
    }
}

sales_management/resources/views/admin/delivery_transaction/create.blade.php
@extends('admin.layouts.app')

@section('head')
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/new-article.css') }}">
@endsection

@section('content')
<div id="content">
    <header class="clearfix">
        <h2 class="pull-left page_title">Create New delivery transaction</h2>
        <a class="btn btn-sm btn-primary pull-right" href="{{ route('delivery-transaction.index') }}" role="button">Back</a>
    </header>

    <div class="content-inner">
        <div class="form-wrapper">
            <form class="form-horizontal" action="{{ route('delivery-transaction.store') }}" method="POST">
                @csrf
                <div class="box-body">

                @if($errors->any())
                    <div class="form-group {{ $errors->has('receipt_code') ? 'has-error' : 'has-success' }}">
                @else
                    <div class="form-group">
                @endif
                    <label for="" class="col-sm-2 control-label">Receipt Code</label>
                    <div class="col-sm-10">
                        <input type="text" name="receipt_code" class="form-control" id="" placeholder="Receipt Code" value="{{ old('receipt_code') }}">
                        <span class="help-block">{{ $errors->first('receipt_code') }}</span>
                    </div>
                </div>

                @if($errors->any())
                    <div class="form-group {{ $errors->has('agent_address') ? 'has-error' : 'has-success' }}">
                @else
                    <div class="form-group">
                @endif
                    <label for="" class="col-sm-2 control-label">Agent Address</label>
                    <div class="col-sm-10">
                        <input type="text" name="agent_address" class="form-control" id="" placeholder="Agent Address" value="{{ old('agent_address') }}">
                        <span class="help-block">{{ $errors->first('agent_address') }}</span>
                    </div>
                </div>

                @if($errors->any())
                    <div class="form-group {{ $errors->has('bill_to') ? 'has-error' : 'has-success' }}">
                @else
                    <div class="form-group">
                @endif
                    <label for="" class="col-sm-2 control-label">Bill To</label>
                    <div class="col-sm-10">
                        <input type="text" name="bill_to" class="form-control" id="" placeholder="Bill To" value="{{ old('bill_to') }}">
                        <span class="help-block">{{ $errors->first('bill_to') }}</span>
                    </div>
                </div>

                @if($errors->any())
                    <div class="form-group {{ $errors->has('ship_to') ? 'has-error' : 'has-success' }}">
                @else
                    <div class="form-group">
                @endif
                    <label for="" class="col-sm-2 control-label">Ship To</label>
                    <div class="col-sm-10">
                        <input type="text" name="ship_to" class="form-control" id="" placeholder="Ship To" value="{{ old('ship_to') }}">
                        <span class="help-block">{{ $errors->first('ship_to') }}</span>
                    </div>
                </div>

                @if($errors->any())
                    <div class="form-group {{ $errors->has('service_id') ? 'has-error' : 'has-success' }}">
                @else
                    <div class="form-group">
                @endif
                    <label for="" class="col-sm-2 control-label">Ship To</label>
                    <div class="col-sm-10">
                        <select name="service_id" id="" class="form-control">
                            <option value="">choose service</option>
                            @foreach($services as $service)
                                <option value="{{ $service->id }}">{{ $service->name }}</option>
                            @endforeach
                        </select>
                        <span class="help-block">{{ $errors->first('service_id') }}</span>
                    </div>
                </div>


                @if($errors->any())
                    <div class="form-group {{ $errors->has('address_ship') ? 'has-error' : 'has-success' }}">
                @else
                    <div class="form-group">
                @endif
                    <label for="" class="col-sm-2 control-label">Address Ship</label>
                    <div class="col-sm-10">
                        <textarea name="address_ship" id="" cols="30" rows="5" class="form-control" placeholder="Address Ship">{{ old('address_ship') }}</textarea>
                        <span class="help-block">{{ $errors->first('address_ship') }}</span>
                    </div>
                </div>

                @if($errors->any())
                    <div class="form-group {{ $errors->has('due_date') ? 'has-error' : 'has-success' }}">
                @else
                    <div class="form-group">
                @endif
                    <label for="" class="col-sm-2 control-label">Due Date</label>
                    <div class="col-sm-10">
                        <input type="date" name="due_date" class="form-control" id="" placeholder="Due Date" value="{{ old('due_date') }}">
                        <span class="help-block">{{ $errors->first('due_date') }}</span>
                    </div>
                </div>

                </div>
                <!-- /.box-body -->
                <div class="clearfix">
                    <button type="submit" class="btn btn-primary pull-right">Save</button>
                </div>
              <!-- /.box-footer -->
            </form>
        </div>
    </div>
</div>
@endsection

sales_management/resources/views/admin/delivery_transaction/edit.blade.php
@extends('admin.layouts.app')

@section('head')
    <link rel="stylesheet" type="text/css" href="{{ asset('assets/css/new-article.css') }}">
@endsection

@section('content')
<div id="content">
    <header class="clearfix">
        <h2 class="pull-left page_title">Create New delivery transaction</h2>
        <a class="btn btn-sm btn-primary pull-right" href="{{ route('delivery-transaction.index') }}" role="button">Back</a>
    </header>

    <div class="content-inner">
        <div class="form-wrapper">
            <form class="form-horizontal" action="{{ route('delivery-transaction.update',$deliveryTransaction->id) }}" method="POST">
                @csrf
                {{ method_field('PATCH') }}
                <div class="box-body">

                @if($errors->any())
                    <div class="form-group {{ $errors->has('receipt_code') ? 'has-error' : 'has-success' }}">
                @else
                    <div class="form-group">
                @endif
                    <label for="" class="col-sm-2 control-label">Receipt Code</label>
                    <div class="col-sm-10">
                        <input type="text" name="receipt_code" class="form-control" id="" placeholder="Receipt Code" value="{{ $errors->any() ? old('receipt_code') : $deliveryTransaction->receipt_code }}">
                        <span class="help-block">{{ $errors->first('receipt_code') }}</span>
                    </div>
                </div>

                @if($errors->any())
                    <div class="form-group {{ $errors->has('agent_address') ? 'has-error' : 'has-success' }}">
                @else
                    <div class="form-group">
                @endif
                    <label for="" class="col-sm-2 control-label">Agent Address</label>
                    <div class="col-sm-10">
                        <input type="text" name="agent_address" class="form-control" id="" placeholder="Agent Address" value="{{ $errors->any() ? old('agent_address') : $deliveryTransaction->agent_address }}">
                        <span class="help-block">{{ $errors->first('agent_address') }}</span>
                    </div>
                </div>

                @if($errors->any())
                    <div class="form-group {{ $errors->has('bill_to') ? 'has-error' : 'has-success' }}">
                @else
                    <div class="form-group">
                @endif
                    <label for="" class="col-sm-2 control-label">Bill To</label>
                    <div class="col-sm-10">
                        <input type="text" name="bill_to" class="form-control" id="" placeholder="Bill To" value="{{ $errors->any() ? old('bill_to') : $deliveryTransaction->bill_to }}">
                        <span class="help-block">{{ $errors->first('bill_to') }}</span>
                    </div>
                </div>

                @if($errors->any())
                    <div class="form-group {{ $errors->has('ship_to') ? 'has-error' : 'has-success' }}">
                @else
                    <div class="form-group">
                @endif
                    <label for="" class="col-sm-2 control-label">Ship To</label>
                    <div class="col-sm-10">
                        <input type="text" name="ship_to" class="form-control" id="" placeholder="Ship To" value="{{ $errors->any() ? old('ship_to') : $deliveryTransaction->ship_to }}">
                        <span class="help-block">{{ $errors->first('ship_to') }}</span>
                    </div>
                </div>

                @if($errors->any())
                    <div class="form-group {{ $errors->has('address_ship') ? 'has-error' : 'has-success' }}">
                @else
                    <div class="form-group">
                @endif
                    <label for="" class="col-sm-2 control-label">Address Ship</label>
                    <div class="col-sm-10">
                        <textarea name="address_ship" id="" cols="30" rows="5" class="form-control" placeholder="Address Ship">{{ $errors->any() ? old('address_ship') : $deliveryTransaction->address_ship }}</textarea>
                        <span class="help-block">{{ $errors->first('address_ship') }}</span>
                    </div>
                </div>

                @if($errors->any())
                    <div class="form-group {{ $errors->has('due_date') ? 'has-error' : 'has-success' }}">
                @else
                    <div class="form-group">
                @endif
                    <label for="" class="col-sm-2 control-label">Due Date</label>
                    <div class="col-sm-10">
                        <input type="date" name="due_date" class="form-control" id="" placeholder="Due Date" value="{{ $errors->any() ? old('due_date') : $deliveryTransaction->due_date }}">
                        <span class="help-block">{{ $errors->first('due_date') }}</span>
                    </div>
                </div>

                </div>
                <!-- /.box-body -->
                <div class="clearfix">
                    <button type="submit" class="btn btn-primary pull-right">Save</button>
                </div>
              <!-- /.box-footer -->
            </form>
        </div>
    </div>
</div>
@endsection

sales_management/resources/views/admin/delivery_transaction/index.blade.php
@extends('admin.layouts.app')

@section('head')
<link rel="stylesheet" href="{{ asset('assets/css/index.css') }}">
@endsection

@section('content')
<div id="dashboard-con">
    <div class="row">
        <div class="col-md-12 dashboard-left-cell">
            <div class="admin-content-con">
            <header class="clearfix">
                <h5 class="pull-left page_title">Delivery Transaction</h5>
                <a class="btn btn-sm btn-primary pull-right" href="{{ route('delivery-transaction.create') }}" role="button">Create new Delivery</a>
            </header>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>no</th>
                        <th>receipt code</th>
                        <th>agent address</th>
                        <th>bill to</th>
                        <th>ship to</th>
                        <th>service</th>
                        <th>due date</th>
                        <th>action</th>
                    </tr>
                </thead>
                <tbody>
                @foreach($results as $result)
                    <tr>
                        <td>no</td>
                        <td>{{ $result->receipt_code }}</td>
                        <td>{{ $result->agent_address }}</td>
                        <td>{{ $result->bill_to }}</td>
                        <td>{{ $result->ship_to }}</td>
                        <td>{{ $result->service->name }}</td>
                        <td>{{ $result->due_date }}</td>
                        <td>
                            {{-- <a class="btn btn-xs btn-warning" href="{{ route('delivery-transaction.edit',$result->id) }}" role="button">edit</a> --}}
                            <a class="btn btn-xs btn-primary" href="{{ route('delivery-transaction.show',$result->id) }}" role="button">view</a>
                            {{-- <form action="{{ route('delivery-transaction.destroy',$result->id) }}" method="POST" style="display:inline;">
                                @csrf
                                {{ method_field('DELETE') }}
                                <button class="btn btn-xs btn-danger">del</button>    
                            </form> --}}
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            <div class="clearfix">
            <a href="#" class="pull-right text-link">view all delivery transaction</a>
            </div>
            </div>
        </div>
    </div>
</div>
@endsection

sales_management/resources/views/admin/delivery_transaction/show.blade.php
@extends('admin.layouts.app')

@section('head')
<link rel="stylesheet" href="{{ asset('assets/css/index.css') }}">
@endsection

@section('content')
<div id="dashboard-con">
    <div class="row">
        <div class="col-md-12">
            <div class="admin-content-con clearfix">
                <header class="clearfix">
                <h5 class="pull-left page_title">Detail Delivery Transaction</h5>
                <a class="btn btn-sm btn-primary pull-right" href="{{ route('delivery-transaction.index') }}" role="button">Back</a>
            </header>

                <table class="table table-bordered">
                    <tr>
                        <th>Receipt code</th>
                        <td>{{ $deliveryTransaction->receipt_code }}</td>
                    </tr>
                    <tr>
                        <th>Agent address</th>
                        <td>{{ $deliveryTransaction->agent_address }}</td>
                    </tr>
                    <tr>
                        <th>Bill to</th>
                        <td>{{ $deliveryTransaction->bill_to }}</td>
                    </tr>
                    <tr>
                        <th>Ship to</th>
                        <td>{{ $deliveryTransaction->ship_to }}</td>
                    </tr>
                    <tr>
                        <th>Service</th>
                        <td>{{ $deliveryTransaction->service->name }}</td>
                    </tr>
                    <tr>
                        <th>Address ship</th>
                        <td>{{ $deliveryTransaction->address_ship }}</td>
                    </tr>
                    <tr>
                        <th>Due date</th>
                        <td>{{ $deliveryTransaction->due_date }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

     <div class="row">
        <div class="col-md-12">
            <div class="admin-content-con clearfix">
            <header class="clearfix">
                <h5 class="pull-left page_title">Item Delivery</h5>
                {{-- <a class="btn btn-sm btn-primary pull-right" href="{{ route('item-delivery.create',$deliveryTransaction->id) }}" role="button">Create New Item Delivery</a> --}}
            </header>

                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>item name</th>
                            <th>quantity</th>
                            <th>price</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        @php
                            $total = 0;
                        @endphp
                        @foreach($deliveryTransaction->itemDelivery as $item)
                            @php
                                $total += $item->qty * $item->price;
                            @endphp
                            <tr>
                                <td>{{ $item->item_name }}</td>
                                <td>{{ $item->qty }}</td>
                                <td>{{ number_format($item->price,2) }}</td>
                                <td>{{ number_format($item->qty * $item->price,2) }}</td>
                            </tr>
                        @endforeach
                            <tr>
                                <td>total</td>
                                <td></td>
                                <td></td>
                                <td>{{ number_format($total,2) }}</td>
                            </tr>
                    </body>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection 